# Generated by Django 3.1.2 on 2022-10-24 02:44

import django.contrib.auth.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0009_auto_20221013_1238'),
    ]

    operations = [
        migrations.RenameField(
            model_name='especialidades',
            old_name='Nombre',
            new_name='nombre',
        ),
        migrations.AlterField(
            model_name='paciente',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username'),
        ),
    ]
